"""token_diet: same information, fewer billed tokens."""
from __future__ import annotations

# Keep in sync with `version` in pyproject.toml.
__version__ = "3.28.0"

__all__ = [
    "__version__",
    "AntiPattern",
    "CognitionPlan",
    "ContextClass",
    "DebateResult",
    "Decision",
    "DecisiveAgent",
    "DecomposedResult",
    "FeedMessage",
    "FocusKeeper",
    "FocusReport",
    "Goal",
    "MARKET_CHANNELS",
    "ObsidianVault",
    "RawMessage",
    "ThoughtNode",
    "TotResult",
    "assess_complexity",
    "choose_cognition_strategy",
    "cognitive_solve",
    "decompose_and_solve",
    "multi_agent_debate",
    "tree_of_thoughts",
    "STRUCTPACK_PREAMBLE",
    "TICKER_ALIASES",
    "TelegramMarketFeed",
    "compact_digest",
    "detect_tickers",
    "feed_to_news_items",
    "parse_message",
    "SECTION_NAMES",
    "CALL_TYPES",
    "EDGE_TYPES",
    "AdaptiveContext",
    "AgentContextResult",
    "BenchmarkEntry",
    "BlobCorruptionError",
    "BlobExpiredError",
    "BlobForbiddenError",
    "BlobNotFoundError",
    "BlobStore",
    "BlobTooLargeError",
    "Breakpoint",
    "BudgetDecision",
    "BudgetGuard",
    "CacheBreakpointAnalyzer",
    "CacheReport",
    "CompressedTurn",
    "CompetitorBenchmark",
    "ContentSegment",
    "ContextLedger",
    "ContextManager",
    "Corridor",
    "CriticalFact",
    "DynamicRatioResult",
    "EquivalenceGate",
    "EventStore",
    "Example",
    "FewShotSelector",
    "GateResult",
    "GreenCalculator",
    "GreenMetrics",
    "MemoryEvent",
    "IntelligenceBooster",
    "InvestHub",
    "TinkoffMCP",
    "TinkoffMCPError",
    "LLMConnector",
    "LLMResult",
    "MultiplierResult",
    "OptimizationProposal",
    "OptimizationReport",
    "OptimizationRunner",
    "PROVIDER_PRICES",
    "PriceTable",
    "PromptBuilder",
    "PromptDistiller",
    "RegressionCase",
    "RouteSavings",
    "RouterConfig",
    "RoutingDecision",
    "RequestProfile",
    "Scenario",
    "SectionMetrics",
    "SectionStats",
    "SelectionEntry",
    "SemanticCache",
    "SmartMultiplier",
    "SelfVerifier",
    "SherlockReasoner",
    "TaskMetrics",
    "TokenMeter",
    "TranslationCache",
    "TranslationChoice",
    "Usage",
    "canonical_json",
    "check_critical_facts",
    "classify_and_compress",
    "classify_turn",
    "compress_agent_context",
    "check_fact",
    "choose_language",
    "compare_llm_quality",
    "compress_json",
    "compress_json_ast",
    "compress_ml",
    "compress_prose_aggressive",
    "compress_retrieved_context",
    "compress_tool_output",
    "compress_tool_result_json",
    "compress_with_routing",
    "cosine_similarity",
    "count_tokens",
    "dynamic_pipeline",
    "estimate_mixed_savings",
    "deduplicate_chunks",
    "deterministic_judge",
    "estimate_complexity",
    "extract_events",
    "fingerprint",
    "guarded_records",
    "guarded_tool_schemas",
    "hash_text",
    "mean_ci",
    "never_translate",
    "normalize_question",
    "pack_records",
    "percentile_corridor",
    "PortfolioCommander",
    "PositionPlan",
    "leverage_analysis",
    "plan_position",
    "position_plan",
    "prepare_request",
    "project_fields",
    "reduce_output",
    "render_compressed_context",
    "route_and_estimate",
    "route_query",
    "sherlock_system_prompt",
    "stop_loss_level",
    "structpack_roundtrip_safe",
    "market_open_now",
    "AgentSupervisor",
    "AgentTurn",
    "CommitteeVerdict",
    "CommitteeVote",
    "DividendEvent",
    "InvestmentAnalyzer",
    "InvestmentVerdict",
    "LoopAlert",
    "NeuralScorer",
    "NewsItem",
    "ObsidianMemoryStore",
    "ObsidianNote",
    "PricedInAssessment",
    "RetrievalResult",
    "ScoredChunk",
    "SupervisorState",
    "TELEGRAM_HELP",
    "TEST_PROMPTS",
    "assess_news_from_snippets",
    "assess_news_priced_in",
    "build_events_from_calendar_rows",
    "estimate_memory_savings",
    "score_prompt_sections",
    "strip_noise",
    "supervised_agent_loop",
    "translation_safe",
    "truncate_tool_result",
    "TurnKind",
    "unpack_records",
    "OWNER_ID",
    "telegram_load_token",
    "telegram_run",
    "telegram_send_message",
    "ScreenFrame",
    "PhoneScreen",
    "DesktopScreen",
    "UINode",
    "UniversalScreen",
    "DocsCache",
    "KNOWN_PACKAGES",
    "LiveDocsResult",
    "PruneResult",
    "PrunedTurn",
    "ScrapeResult",
    "docs_bundle",
    "fetch_package_docs",
    "flush_cache",
    "fuzzy_fingerprint",
    "get_live_docs",
    "html_to_text",
    "prune_and_compress",
    "prune_tool_outputs",
    "render_pruned",
    "result_hash",
    "scrape_and_save",
    "scrape_url",
    "BM25Reranker",
    "MapReduceResult",
    "RerankHit",
    "extractive_summarize",
    "map_reduce",
    "rerank_chunks",
    "rerank_library",
    "split_into_chunks",
    "CodeBudget",
    "SYSTEM_PROMPTS",
    "Toolchain",
    "build_toolchain",
    "code_budget",
    "detect_language",
    "protect_code",
    "system_prompt_for",
    "AndroidProject",
    "BuildResult",
    "ToolchainStatus",
    "build_apk",
    "check_toolchain",
    "create_android_project",
    "find_android_jar",
    "find_build_tools",
    "find_sdk",
    "find_sdkmanager",
    "inspect_apk",
    "install_instructions",
    "MinimizeResult",
    "RedundancyReport",
    "analyze_prompt",
    "minimize_system_prompt",
    "optimize_system_prompt",
    "reorder_prompt",
    "ANSWER_FIRST_PROMPT",
    "CHAIN_OF_DRAFT_PROMPT",
    "OverthinkingResult",
    "adaptive_effort_prompt",
    "answer_first_prompt",
    "chain_of_draft_compress",
    "chain_of_draft_prompt",
    "detect_overthinking",
    "estimate_effort",
    "optimize_thinking",
    "CachePolicy",
    "KeepaliveDecision",
    "KeepaliveEconomics",
    "KeepaliveManager",
    "KeepaliveStats",
    "estimate_keepalive_savings",
    "TronCheck",
    "tron_savings",
    "to_tron",
    "to_tron_schemas",
    "tron_roundtrip_safe",
    "Skill",
    "SkillRegistry",
    "default_registry",
    "GOAPAction",
    "GoalPlanner",
    "PlanResult",
    "TrajectoryMemory",
    "WorldState",
    "coding_actions",
    "demo_goal",
    "InteractiveElement",
    "DesignTokens",
    "DocEntry",
    "DocsHit",
    "DocsRetriever",
    "ColumnInfo",
    "TableInfo",
    "Entity",
    "EntityGraph",
    "Relation",
    "extract_interactive_elements",
    "estimate_ui_savings",
    "is_bot_like_ua",
    "render_accessibility_tree",
    "render_ui_context",
    "stealth_fingerprint",
    "closest_key",
    "estimate_design_savings",
    "extract_design_tokens",
    "map_to_tailwind",
    "tailwind_class_for",
    "estimate_docs_savings",
    "compress_schema",
    "estimate_schema_savings",
    "parse_ddl",
    "render_schema",
    "schema_to_prompt_block",
    "extract_entities",
    "ScrapeGraph",
    "ScrapeGraphResult",
    "estimate_scrape_savings",
    "extract_across_chunks",
    "extract_json_ld",
    "extract_meta_tags",
    "extract_schema_fields",
    "ld_flatten",
    "CCRStore",
    "ClaudeMem",
    "MemoryObservation",
    "StrixProfile",
    "Tab",
    "TabManager",
    "GatewayResult",
    "GenerativeGateway",
    "Provider",
    "crush_json",
    "crush_logs",
    "crush_markdown",
    "detect_content_type",
    "estimate_headroom_savings",
    "headroom_compress",
    "headroom_retrieve",
    "estimate_memory_injection_savings",
    "audit_fingerprint",
    "build_profile",
    "is_coherent",
    "rotate_profiles",
    "estimate_tabs_savings",
    "estimate_gateway_savings",
    "normalize_payload",
    "payload_key",
    "CandlePattern",
    "detect_patterns",
    "latest_patterns",
    "patterns_block",
    "single_bar_patterns",
    "three_bar_patterns",
    "two_bar_patterns",
    "ema",
    "mfi",
    "obv",
    "obv_trend",
    "sma",
    "snapshot_block",
    "stochastic",
    "technical_snapshot",
    "williams_r",
    "annualized_volatility",
    "correlation_matrix",
    "historical_var",
    "max_drawdown",
    "position_size",
    "trade_plan",
    "returns_of",
    "risk_block",
    "risk_report",
    "sharpe_ratio",
    "sortino_ratio",
    "trailing_stop",
    "DEFAULT_BASKET",
    "GOLD_PROXIES",
    "SweetSpot",
    "sweet_report",
    "sweet_scan",
    "WebPilotResult",
    "ask_web",
    "extract_relevant",
    "read_page",
    "web_search",
    "MorningBrief",
    "brief",
    "brief_block",
    "WriteState",
    "pulse_comment",
    "pulse_cookies_from_file",
    "pulse_cookies_from_firefox",
    "pulse_like",
    "pulse_post",
    "pulse_validate_text",
    "calibrate_prompt",
    "check_plan_coverage",
    "compress_thought",
    "cove_draft_prompt",
    "cove_synthesis_prompt",
    "escalate",
    "extract_claims",
    "ltm_decompose_prompt",
    "ltm_solve_prompt",
    "plan_and_solve_prompt",
    "plan_steps",
    "retention_prompt",
    "verify_claims",
    "ALERT_FILE",
    "LOG_FILE",
    "GuardConfig",
    "PulsePost",
    "get_post_comments",
    "get_ticker_posts",
    "get_user_posts",
    "parse_post",
    "pulse_digest",
    "pulse_sentiment",
    "search_keywords",
    "monitor_loop",
    "news_block",
    "news_sweep",
    "snapshot",
    "stress_block",
    "stress_test",
    "TangentAlert",
    "RapidContext",
    "analyze_focus",
    "check_action",
    "classify",
    "decide",
    "decide_action",
    "learn_from",
    "quick_action",
    "screenshot",
    "see_and_click",
    "strip_fluff",
    "detect_platform",
    "click_text",
    "FileGraphStore",
    "GraphitiBackend",
    "GraphMemory",
    "extract_numbers",
    "TdqsLinter",
    "TdqsResult",
    "ToolRegistry",
    "ToolSpec",
    "Playbook",
    "PlaybookStore",
    "cleared_marker",
    "history_budget",
    "prune_history",
    "DEFAULT_PROVIDERS",
    "OmniRouter",
    "SubAgentResult",
    "_judge",
    "_split_tasks",
    "Critique",
    "CritiqueResult",
    "DifficultyEstimate",
    "MetaVerdict",
    "UncertaintyFlag",
    "calibrated_verdict",
    "difficulty",
    "flag_uncertainty",
    "metacognition_prompt",
    "prior_confidence",
    "self_critique",
    "BeliefVerdict",
    "FirmUpResult",
    "PersistPlan",
    "belief_prompt",
    "confident_rewrite",
    "earned_confidence",
    "firm_up",
    "persist",
    "rewrite_surrender",
    "strip_apology",
    "Claim",
    "ClaimAudit",
    "HardcodedVerdict",
    "Incoherence",
    "Verification",
    "audit_text",
    "check_coherence",
    "claim_check_prompt",
    "find_hardcoded_verdicts",
    "verify_claim",
    "DroidCoordinator",
    "DROID_REGISTRY",
    "DroidSpec",
    "Handoff",
    "RepoKnowledge",
    "droid_ambiguity",
    "droid_build_knowledge",
    "droid_classify",
    "droid_plan",
    "droid_status_block",
    "droid_resolve",
    "Case",
    "analogy_keywords",
    "analogy_prompt",
    "find_analogies",
    "step_back_prompt",
    "step_back_question",
    "BreakoutResult",
    "detect_breakout",
    "momentum_lean",
    "rate_of_change",
    "company_keywords",
    "from_fresh_news",
    "from_pulse",
    "gather_sentiment_texts",
    "full_plan",
    "history",
    "journal_block",
    "record",
    "full_status",
    "render_status",
    "AuditChain",
    "AuditEntry",
    "EventBatcher",
    "FlushBatch",
    "QueuedEvent",
    "WorkflowEngine",
    "cron_matches",
    "evaluate_condition",
    "init_rules",
    "is_market_open",
    "is_private_ip",
    "is_trading_day",
    "parse_workflow",
    "watch",
    "build_handoff",
    "compress_history",
    "extract_facts",
    "render_handoff",
    "search_vault",
    "rank",
    "autocomplete",
    "hybrid_search",
    "SecurityAudit",
    "GlobalVars",
    "expand",
    "set_var",
    "get_var",
    "ask_omni",
    "OMNI_ROLES",
    "available_providers",
    "detect_providers",
    "providers_ask_any",
    "providers_ask_all",
    "CachePlan",
    "align_prefix",
    "mark_static",
    "plan_cache",
    "relocate",
    "ClonedElement",
    "clone_complete",
    "clone_skeleton",
    "expand_layer",
    "render",
    "savings_report",
    "TurboReport",
    "turbo",
    "report_text",
    "top_memory_processes",
    "CreativeVerdict",
    "DreamReport",
    "InvertedDictionary",
    "creative_solve",
    "dream_consolidate",
    "haiku_compress",
    "CodeBlock",
    "HealPlan",
    "heal",
    "heal_cli",
    "verify_docs",
    "render_report",
    "SpendForecast",
    "UsageDay",
    "Anomaly",
    "forecast_spend",
    "forecast_from_pairs",
    "budget_runway",
    "Holding",
    "RebalancePlan",
    "TradeAdvice",
    "rebalance_plan",
    "drift_report",
]

_LAZY_IMPORTS = {
    "CodeBlock": ("token_diet.doc_guardian", "CodeBlock"),
    "CreativeVerdict": ("token_diet.creative_mind", "CreativeVerdict"),
    "DreamReport": ("token_diet.creative_mind", "DreamReport"),
    "HealPlan": ("token_diet.auto_heal", "HealPlan"),
    "InvertedDictionary": ("token_diet.creative_mind", "InvertedDictionary"),
    "creative_solve": ("token_diet.creative_mind", "creative_solve"),
    "dream_consolidate": ("token_diet.creative_mind", "dream_consolidate"),
    "haiku_compress": ("token_diet.creative_mind", "haiku_compress"),
    "heal": ("token_diet.auto_heal", "heal"),
    "heal_cli": ("token_diet.auto_heal", "heal_cli"),
    "render_report": ("token_diet.doc_guardian", "render_report"),
    "verify_docs": ("token_diet.doc_guardian", "verify_docs"),
    "ALERT_FILE": ("token_diet.market_guard", "ALERT_FILE"),
    "ANSWER_FIRST_PROMPT": ("token_diet.efficient_thinking", "ANSWER_FIRST_PROMPT"),
    "AdaptiveContext": ("token_diet.context_memory", "AdaptiveContext"),
    "AgentContextResult": ("token_diet.agent_context", "AgentContextResult"),
    "AgentSupervisor": ("token_diet.agent_supervisor", "AgentSupervisor"),
    "AgentTurn": ("token_diet.agent_supervisor", "AgentTurn"),
    "AndroidProject": ("token_diet.apk_builder", "AndroidProject"),
    "AntiPattern": ("token_diet.mistake_learner", "AntiPattern"),
    "AuditChain": ("token_diet.audit_chain", "AuditChain"),
    "AuditEntry": ("token_diet.audit_chain", "AuditEntry"),
    "AutoThrottle": ("token_diet.scrapling_diet", "AutoThrottle"),
    "BM25Reranker": ("token_diet.bm25_reranker", "BM25Reranker"),
    "BacktestResult": ("token_diet.trading_robot", "BacktestResult"),
    "BatchEvent": ("token_diet.event_batcher", "BatchEvent"),
    "BeliefVerdict": ("token_diet.self_belief", "BeliefVerdict"),
    "BenchmarkEntry": ("token_diet.competitor_benchmark", "BenchmarkEntry"),
    "BlobCorruptionError": ("token_diet.core", "BlobCorruptionError"),
    "BlobExpiredError": ("token_diet.core", "BlobExpiredError"),
    "BlobForbiddenError": ("token_diet.core", "BlobForbiddenError"),
    "BlobNotFoundError": ("token_diet.core", "BlobNotFoundError"),
    "BlobStore": ("token_diet.core", "BlobStore"),
    "BlobTooLargeError": ("token_diet.core", "BlobTooLargeError"),
    "BoostAllocation": ("token_diet.intelligence_booster", "BoostAllocation"),
    "BoostedResult": ("token_diet.intelligence_booster", "BoostedResult"),
    "BreakoutResult": ("token_diet.momentum", "BreakoutResult"),
    "Breakpoint": ("token_diet.cache_breakpoints", "Breakpoint"),
    "BudgetDecision": ("token_diet.core", "BudgetDecision"),
    "BudgetGuard": ("token_diet.core", "BudgetGuard"),
    "BuildResult": ("token_diet.apk_builder", "BuildResult"),
    "CALL_TYPES": ("token_diet.core", "CALL_TYPES"),
    "CCRStore": ("token_diet.headroom", "CCRStore"),
    "CHAIN_OF_DRAFT_PROMPT": ("token_diet.efficient_thinking", "CHAIN_OF_DRAFT_PROMPT"),
    "CacheBreakpointAnalyzer": ("token_diet.cache_breakpoints", "CacheBreakpointAnalyzer"),
    "CachePlan": ("token_diet.cache_master", "CachePlan"),
    "CachePolicy": ("token_diet.cache_keepalive", "CachePolicy"),
    "CacheReport": ("token_diet.cache_breakpoints", "CacheReport"),
    "CandlePattern": ("token_diet.candlestick_patterns", "CandlePattern"),
    "CapturedResponse": ("token_diet.scrapling_diet", "CapturedResponse"),
    "Case": ("token_diet.step_back", "Case"),
    "ChainResult": ("token_diet.intelligence_chain", "ChainResult"),
    "Claim": ("token_diet.claim_check", "Claim"),
    "ClaimAudit": ("token_diet.claim_check", "ClaimAudit"),
    "ClaudeMem": ("token_diet.claude_mem", "ClaudeMem"),
    "ClonedElement": ("token_diet.progressive_clone", "ClonedElement"),
    "CodeBudget": ("token_diet.polyglot", "CodeBudget"),
    "CognitionPlan": ("token_diet.cognition_arsenal", "CognitionPlan"),
    "ColumnInfo": ("token_diet.schema_compressor", "ColumnInfo"),
    "CommitteeVerdict": ("token_diet.investment_analyzer", "CommitteeVerdict"),
    "CommitteeVote": ("token_diet.investment_analyzer", "CommitteeVote"),
    "CompetitorBenchmark": ("token_diet.competitor_benchmark", "CompetitorBenchmark"),
    "CompressedTurn": ("token_diet.agent_context", "CompressedTurn"),
    "ConfluenceReport": ("token_diet.market_intelligence", "ConfluenceReport"),
    "ContentSegment": ("token_diet.dynamic_ratio", "ContentSegment"),
    "ContextClass": ("token_diet.rapid_context", "ContextClass"),
    "ContextLedger": ("token_diet.core", "ContextLedger"),
    "ContextManager": ("token_diet.context_memory", "ContextManager"),
    "Corridor": ("token_diet.trading_robot", "Corridor"),
    "CriticalFact": ("token_diet.equivalence_gate", "CriticalFact"),
    "Critique": ("token_diet.metacognition", "Critique"),
    "CritiqueResult": ("token_diet.metacognition", "CritiqueResult"),
    "DEFAULT_BASKET": ("token_diet.sweet_spot", "DEFAULT_BASKET"),
    "DEFAULT_PROVIDERS": ("token_diet.omniroute", "DEFAULT_PROVIDERS"),
    "DROID_REGISTRY": ("token_diet.factory_droid", "DROIDS"),
    "DebateResult": ("token_diet.cognition_arsenal", "DebateResult"),
    "Decision": ("token_diet.commander", "Decision"),
    "DecisiveAgent": ("token_diet.decisive_agent", "DecisiveAgent"),
    "DecomposedResult": ("token_diet.cognition_arsenal", "DecomposedResult"),
    "DesignTokens": ("token_diet.design_tokens", "DesignTokens"),
    "DesktopScreen": ("token_diet.universal_screen", "DesktopScreen"),
    "DifficultyEstimate": ("token_diet.metacognition", "DifficultyEstimate"),
    "DiskResponseCache": ("token_diet.scrapling_diet", "DiskResponseCache"),
    "DividendEvent": ("token_diet.investment_analyzer", "DividendEvent"),
    "DocEntry": ("token_diet.docs_retriever", "DocEntry"),
    "DocsCache": ("token_diet.live_docs", "DocsCache"),
    "DocsHit": ("token_diet.docs_retriever", "DocsHit"),
    "DocsRetriever": ("token_diet.docs_retriever", "DocsRetriever"),
    "DroidCoordinator": ("token_diet.factory_droid", "Coordinator"),
    "DroidSpec": ("token_diet.factory_droid", "DroidSpec"),
    "DynamicRatioResult": ("token_diet.dynamic_ratio", "DynamicRatioResult"),
    "EDGE_TYPES": ("token_diet.obsidian_memory", "EDGE_TYPES"),
    "Entity": ("token_diet.entity_graph", "Entity"),
    "EntityGraph": ("token_diet.entity_graph", "EntityGraph"),
    "EquivalenceGate": ("token_diet.equivalence_gate", "EquivalenceGate"),
    "EventBatcher": ("token_diet.event_batcher", "EventBatcher"),
    "EventStore": ("token_diet.context_memory", "EventStore"),
    "Example": ("token_diet.few_shot_selector", "Example"),
    "FeedMessage": ("token_diet.telegram_market_feed", "FeedMessage"),
    "FewShotSelector": ("token_diet.few_shot_selector", "FewShotSelector"),
    "FileGraphStore": ("token_diet.graph_memory", "FileGraphStore"),
    "Finding": ("token_diet.code_quality", "Finding"),
    "FirmUpResult": ("token_diet.self_belief", "FirmUpResult"),
    "FlushBatch": ("token_diet.event_batcher", "FlushBatch"),
    "FocusKeeper": ("token_diet.focus_keeper", "FocusKeeper"),
    "FocusReport": ("token_diet.focus_keeper", "FocusReport"),
    "GENESIS_HASH": ("token_diet.audit_chain", "GENESIS_HASH"),
    "GOAPAction": ("token_diet.goal_planner", "GOAPAction"),
    "GOLD_PROXIES": ("token_diet.sweet_spot", "GOLD_PROXIES"),
    "GateResult": ("token_diet.equivalence_gate", "GateResult"),
    "GatewayResult": ("token_diet.open_generative", "GatewayResult"),
    "GenerativeGateway": ("token_diet.open_generative", "GenerativeGateway"),
    "GitTaskTracker": ("token_diet.intelligence_chain", "GitTaskTracker"),
    "GlobalVars": ("token_diet.global_vars", "GlobalVars"),
    "Goal": ("token_diet.focus_keeper", "Goal"),
    "GoalPlanner": ("token_diet.goal_planner", "GoalPlanner"),
    "GraphMemory": ("token_diet.graph_memory", "GraphMemory"),
    "GraphitiBackend": ("token_diet.graph_memory", "GraphitiBackend"),
    "GreenCalculator": ("token_diet.green_calculator", "GreenCalculator"),
    "GreenMetrics": ("token_diet.green_calculator", "GreenMetrics"),
    "GuardConfig": ("token_diet.market_guard", "GuardConfig"),
    "Handoff": ("token_diet.factory_droid", "Handoff"),
    "HardcodedVerdict": ("token_diet.claim_check", "HardcodedVerdict"),
    "Incoherence": ("token_diet.claim_check", "Incoherence"),
    "IntelligenceBooster": ("token_diet.intelligence_booster", "IntelligenceBooster"),
    "IntelligenceChain": ("token_diet.intelligence_chain", "IntelligenceChain"),
    "InteractiveElement": ("token_diet.ui_context", "InteractiveElement"),
    "IntervalSignal": ("token_diet.trading_robot", "IntervalSignal"),
    "InvestHub": ("token_diet.invest_hub", "InvestHub"),
    "InvestmentAnalyzer": ("token_diet.investment_analyzer", "InvestmentAnalyzer"),
    "InvestmentVerdict": ("token_diet.investment_analyzer", "InvestmentVerdict"),
    "KNOWN_ACTIONS": ("token_diet.audit_chain", "KNOWN_ACTIONS"),
    "KNOWN_FIGI": ("token_diet.tinkoff_invest", "KNOWN_FIGI"),
    "KNOWN_PACKAGES": ("token_diet.live_docs", "KNOWN_PACKAGES"),
    "KeepaliveDecision": ("token_diet.cache_keepalive", "KeepaliveDecision"),
    "KeepaliveEconomics": ("token_diet.cache_keepalive", "KeepaliveEconomics"),
    "KeepaliveManager": ("token_diet.cache_keepalive", "KeepaliveManager"),
    "KeepaliveStats": ("token_diet.cache_keepalive", "KeepaliveStats"),
    "LIVE_SCAN_TICKERS": ("token_diet.live_scan", "LIQUID_TICKERS"),
    "LLMConnector": ("token_diet.llm_connector", "LLMConnector"),
    "LLMResult": ("token_diet.llm_connector", "LLMResult"),
    "LOG_FILE": ("token_diet.market_guard", "LOG_FILE"),
    "LinkExtractor": ("token_diet.scrapling_diet", "LinkExtractor"),
    "LiveDocsResult": ("token_diet.live_docs", "LiveDocsResult"),
    "LoopAlert": ("token_diet.agent_supervisor", "LoopAlert"),
    "MARKET_CHANNELS": ("token_diet.telegram_market_feed", "MARKET_CHANNELS"),
    "MCP_CONFIG_FILES": ("token_diet.auto_setup", "MCP_CONFIG_FILES"),
    "MaCrossSignal": ("token_diet.trading_robot", "MaCrossSignal"),
    "MapReduceResult": ("token_diet.map_reduce", "MapReduceResult"),
    "MemoryEvent": ("token_diet.context_memory", "MemoryEvent"),
    "MemoryHooks": ("token_diet.intelligence_chain", "MemoryHooks"),
    "MemoryObservation": ("token_diet.claude_mem", "MemoryObservation"),
    "MetaVerdict": ("token_diet.metacognition", "MetaVerdict"),
    "MinimizeResult": ("token_diet.context_engineering", "MinimizeResult"),
    "MistakeAlert": ("token_diet.mistake_learner", "MistakeAlert"),
    "MistakeLearner": ("token_diet.mistake_learner", "MistakeLearner"),
    "ModelPrompt": ("token_diet.intelligence_chain", "ModelPrompt"),
    "MoexCandle": ("token_diet.moex_feed", "MoexCandle"),
    "MoexDividend": ("token_diet.moex_feed", "MoexDividend"),
    "MoexFeed": ("token_diet.moex_feed", "MoexFeed"),
    "MoexQuote": ("token_diet.moex_feed", "MoexQuote"),
    "MorningBrief": ("token_diet.morning_brief", "MorningBrief"),
    "MultiplierResult": ("token_diet.smart_multiplier", "MultiplierResult"),
    "NeuralScorer": ("token_diet.neural_scorer", "NeuralScorer"),
    "NewsItem": ("token_diet.investment_analyzer", "NewsItem"),
    "OMNI_ROLES": ("token_diet.model_army", "OMNI_ROLES"),
    "OWNER_ID": ("token_diet.telegram_commander", "OWNER_ID"),
    "ObsidianMemoryStore": ("token_diet.obsidian_memory", "ObsidianMemoryStore"),
    "ObsidianNote": ("token_diet.obsidian_memory", "ObsidianNote"),
    "ObsidianVault": ("token_diet.obsidian_vault", "ObsidianVault"),
    "OmniRouter": ("token_diet.omniroute", "OmniRouter"),
    "OptimizationProposal": ("token_diet.optimization_runner", "OptimizationProposal"),
    "OptimizationReport": ("token_diet.optimization_runner", "OptimizationReport"),
    "OptimizationRunner": ("token_diet.optimization_runner", "OptimizationRunner"),
    "OverthinkingResult": ("token_diet.efficient_thinking", "OverthinkingResult"),
    "PROVIDER_PRICES": ("token_diet.llm_connector", "PROVIDER_PRICES"),
    "PersistPlan": ("token_diet.self_belief", "PersistPlan"),
    "PhoneScreen": ("token_diet.universal_screen", "PhoneScreen"),
    "PlanResult": ("token_diet.goal_planner", "PlanResult"),
    "Playbook": ("token_diet.playbooks", "Playbook"),
    "PlaybookStore": ("token_diet.playbooks", "PlaybookStore"),
    "PortfolioCommander": ("token_diet.portfolio_commander", "PortfolioCommander"),
    "PortfolioPosition": ("token_diet.tinkoff_invest", "PortfolioPosition"),
    "PositionPlan": ("token_diet.portfolio_commander", "PositionPlan"),
    "PriceTable": ("token_diet.core", "PriceTable"),
    "PricedInAssessment": ("token_diet.investment_analyzer", "PricedInAssessment"),
    "PromptBuilder": ("token_diet.core", "PromptBuilder"),
    "PromptDistiller": ("token_diet.prompt_distiller", "PromptDistiller"),
    "Provider": ("token_diet.omniroute", "Provider"),
    "ProxyRotator": ("token_diet.scrapling_diet", "ProxyRotator"),
    "PruneResult": ("token_diet.tool_output_pruner", "PruneResult"),
    "PrunedTurn": ("token_diet.tool_output_pruner", "PrunedTurn"),
    "PulsePost": ("token_diet.pulse_reader", "PulsePost"),
    "QueuedEvent": ("token_diet.event_batcher", "QueuedEvent"),
    "REVIEW_CHECKLIST": ("token_diet.code_quality", "REVIEW_CHECKLIST"),
    "RUS_HOLIDAYS_2026": ("token_diet.date_anchor", "RUS_HOLIDAYS_2026"),
    "RapidContext": ("token_diet.rapid_context", "RapidContext"),
    "RawMessage": ("token_diet.telegram_market_feed", "RawMessage"),
    "RedundancyReport": ("token_diet.context_engineering", "RedundancyReport"),
    "RegressionCase": ("token_diet.equivalence_gate", "RegressionCase"),
    "Relation": ("token_diet.entity_graph", "Relation"),
    "RepoKnowledge": ("token_diet.factory_droid", "RepoKnowledge"),
    "RequestProfile": ("token_diet.optimization_runner", "RequestProfile"),
    "RerankHit": ("token_diet.bm25_reranker", "RerankHit"),
    "RetrievalResult": ("token_diet.obsidian_memory", "RetrievalResult"),
    "RouteSavings": ("token_diet.model_router", "RouteSavings"),
    "RouterConfig": ("token_diet.model_router", "RouterConfig"),
    "RoutingDecision": ("token_diet.model_router", "RoutingDecision"),
    "SECTION_NAMES": ("token_diet.core", "SECTION_NAMES"),
    "STRUCTPACK_PREAMBLE": ("token_diet.core", "STRUCTPACK_PREAMBLE"),
    "SYSTEM_PROMPTS": ("token_diet.polyglot", "SYSTEM_PROMPTS"),
    "Scenario": ("token_diet.smart_multiplier", "Scenario"),
    "ScoredChunk": ("token_diet.neural_scorer", "ScoredChunk"),
    "ScrapeGraph": ("token_diet.scrape_graph", "ScrapeGraph"),
    "ScrapeGraphResult": ("token_diet.scrape_graph", "ScrapeGraphResult"),
    "ScrapeResult": ("token_diet.clean_scraper", "ScrapeResult"),
    "ScreenFrame": ("token_diet.universal_screen", "ScreenFrame"),
    "SectionMetrics": ("token_diet.optimization_runner", "SectionMetrics"),
    "SectionStats": ("token_diet.prompt_distiller", "SectionStats"),
    "SecurityAudit": ("token_diet.security_audit", "SecurityAudit"),
    "SelectionEntry": ("token_diet.context_memory", "SelectionEntry"),
    "SelfVerifier": ("token_diet.sherlock_reasoner", "SelfVerifier"),
    "SemanticCache": ("token_diet.core", "SemanticCache"),
    "ServerStats": ("token_diet.server", "ServerStats"),
    "SherlockReasoner": ("token_diet.sherlock_reasoner", "SherlockReasoner"),
    "SignalResult": ("token_diet.market_intelligence", "SignalResult"),
    "Skill": ("token_diet.lazy_skills", "Skill"),
    "SkillRegistry": ("token_diet.lazy_skills", "SkillRegistry"),
    "SmartMultiplier": ("token_diet.smart_multiplier", "SmartMultiplier"),
    "StrixProfile": ("token_diet.strix_stealth", "StrixProfile"),
    "SubAgentResult": ("token_diet.omniroute", "SubAgentResult"),
    "SupervisorState": ("token_diet.agent_supervisor", "SupervisorState"),
    "SweetSpot": ("token_diet.sweet_spot", "SweetSpot"),
    "TELEGRAM_HELP": ("token_diet.telegram_commander", "HELP"),
    "TELEGRAM_MCP_DIR": ("token_diet.auto_setup", "TELEGRAM_MCP_DIR"),
    "TELEGRAM_MCP_REPO": ("token_diet.auto_setup", "TELEGRAM_MCP_REPO"),
    "TEST_PROMPTS": ("token_diet.competitor_benchmark", "TEST_PROMPTS"),
    "TICKER_ALIASES": ("token_diet.telegram_market_feed", "TICKER_ALIASES"),
    "TOOLS": ("token_diet.auto_setup", "TOOLS"),
    "Tab": ("token_diet.ponytail", "Tab"),
    "TabManager": ("token_diet.ponytail", "TabManager"),
    "TableInfo": ("token_diet.schema_compressor", "TableInfo"),
    "TangentAlert": ("token_diet.focus_keeper", "TangentAlert"),
    "TaskMetrics": ("token_diet.optimization_runner", "TaskMetrics"),
    "TdqsLinter": ("token_diet.tool_search", "TdqsLinter"),
    "TdqsResult": ("token_diet.tool_search", "TdqsResult"),
    "TelegramMarketFeed": ("token_diet.telegram_market_feed", "TelegramMarketFeed"),
    "ThoughtNode": ("token_diet.cognition_arsenal", "ThoughtNode"),
    "TinkoffCandle": ("token_diet.tinkoff_invest", "TinkoffCandle"),
    "TinkoffInvest": ("token_diet.tinkoff_invest", "TinkoffInvest"),
    "TinkoffMCP": ("token_diet.tinkoff_mcp", "TinkoffMCP"),
    "TinkoffMCPError": ("token_diet.tinkoff_mcp", "TinkoffMCPError"),
    "TinkoffQuote": ("token_diet.tinkoff_invest", "TinkoffQuote"),
    "TokenMeter": ("token_diet.core", "TokenMeter"),
    "ToolConfig": ("token_diet.auto_setup", "ToolConfig"),
    "ToolRegistry": ("token_diet.tool_search", "ToolRegistry"),
    "ToolSpec": ("token_diet.tool_search", "ToolSpec"),
    "Toolchain": ("token_diet.polyglot", "Toolchain"),
    "ToolchainStatus": ("token_diet.apk_builder", "ToolchainStatus"),
    "TotResult": ("token_diet.cognition_arsenal", "TotResult"),
    "Trade": ("token_diet.trading_robot", "Trade"),
    "TradingSignal": ("token_diet.market_intelligence", "TradingSignal"),
    "TrajectoryMemory": ("token_diet.goal_planner", "TrajectoryMemory"),
    "TranslationCache": ("token_diet.context_memory", "TranslationCache"),
    "TranslationChoice": ("token_diet.context_memory", "TranslationChoice"),
    "TronCheck": ("token_diet.tron_format", "TronCheck"),
    "TurboReport": ("token_diet.system_turbo", "TurboReport"),
    "TurnKind": ("token_diet.agent_context", "TurnKind"),
    "UINode": ("token_diet.universal_screen", "UINode"),
    "UncertaintyFlag": ("token_diet.metacognition", "UncertaintyFlag"),
    "UniversalScreen": ("token_diet.universal_screen", "UniversalScreen"),
    "Usage": ("token_diet.core", "Usage"),
    "Verification": ("token_diet.claim_check", "Verification"),
    "VerificationResult": ("token_diet.intelligence_chain", "VerificationResult"),
    "VerifierResult": ("token_diet.sherlock_reasoner", "VerifierResult"),
    "VolumeProfileResult": ("token_diet.trading_robot", "VolumeProfileResult"),
    "WORKFLOW_ACTIONS": ("token_diet.workflow_engine", "KNOWN_ACTIONS"),
    "WORKFLOW_TRIGGERS": ("token_diet.workflow_engine", "KNOWN_TRIGGERS"),
    "WebPilotResult": ("token_diet.webpilot", "WebPilotResult"),
    "WorkflowEngine": ("token_diet.workflow_engine", "WorkflowEngine"),
    "WorldState": ("token_diet.goal_planner", "WorldState"),
    "WriteState": ("token_diet.pulse_writer", "WriteState"),
    "_judge": ("token_diet.omniroute", "_judge"),
    "_split_tasks": ("token_diet.omniroute", "_split_tasks"),
    "adaptive_effort_prompt": ("token_diet.efficient_thinking", "adaptive_effort_prompt"),
    "adaptive_select": ("token_diet.scrapling_diet", "adaptive_select"),
    "aggregate_sentiment": ("token_diet.market_intelligence", "aggregate_sentiment"),
    "align_prefix": ("token_diet.cache_master", "align_prefix"),
    "analogy_keywords": ("token_diet.step_back", "analogy_keywords"),
    "analogy_prompt": ("token_diet.step_back", "analogy_prompt"),
    "analyze_focus": ("token_diet.focus_keeper", "analyze_focus"),
    "analyze_prompt": ("token_diet.context_engineering", "analyze_prompt"),
    "analyze_signals": ("token_diet.market_intelligence", "analyze_signals"),
    "annualized_volatility": ("token_diet.risk_metrics", "annualized_volatility"),
    "answer_first_prompt": ("token_diet.efficient_thinking", "answer_first_prompt"),
    "arsenal_categories": ("token_diet.rick_panel", "categories"),
    "arsenal_find": ("token_diet.rick_panel", "find"),
    "arsenal_panel": ("token_diet.rick_panel", "panel_block"),
    "ask_gemini": ("token_diet.model_army", "ask_gemini"),
    "ask_omni": ("token_diet.model_army", "ask_omni"),
    "ask_web": ("token_diet.webpilot", "ask_web"),
    "assess_complexity": ("token_diet.cognition_arsenal", "assess_complexity"),
    "assess_news_from_snippets": ("token_diet.investment_analyzer", "assess_news_from_snippets"),
    "assess_news_priced_in": ("token_diet.investment_analyzer", "assess_news_priced_in"),
    "audit_fingerprint": ("token_diet.strix_stealth", "audit_fingerprint"),
    "audit_text": ("token_diet.claim_check", "audit_text"),
    "autocomplete": ("token_diet.hybrid_search", "autocomplete"),
    "autopilot_check_entry": ("token_diet.autopilot", "check_entry"),
    "autopilot_check_stop": ("token_diet.autopilot", "check_stop"),
    "available_providers": ("token_diet.provider_registry", "available_providers"),
    "backtest": ("token_diet.trading_robot", "backtest"),
    "belief_prompt": ("token_diet.self_belief", "belief_prompt"),
    "brain_decision": ("token_diet.trading_brain", "decide"),
    "brain_scan": ("token_diet.trading_brain", "scan_all"),
    "brief": ("token_diet.morning_brief", "brief"),
    "brief_block": ("token_diet.morning_brief", "brief_block"),
    "browser_api_grab": ("token_diet.scrapling_diet", "browser_api_grab"),
    "build_apk": ("token_diet.apk_builder", "build_apk"),
    "build_events_from_calendar_rows": ("token_diet.investment_analyzer", "build_events_from_calendar_rows"),
    "build_handoff": ("token_diet.session_handoff", "build_handoff"),
    "build_profile": ("token_diet.strix_stealth", "build_profile"),
    "build_review_prompt": ("token_diet.code_quality", "build_review_prompt"),
    "build_toolchain": ("token_diet.polyglot", "build_toolchain"),
    "cached_fetch": ("token_diet.scrapling_diet", "cached_fetch"),
    "calibrate_prompt": ("token_diet.reasoning_kit", "calibrate_prompt"),
    "calibrated_verdict": ("token_diet.metacognition", "calibrated_verdict"),
    "canonical_json": ("token_diet.audit_chain", "canonical_json"),
    "chain_of_draft_compress": ("token_diet.efficient_thinking", "chain_of_draft_compress"),
    "chain_of_draft_prompt": ("token_diet.efficient_thinking", "chain_of_draft_prompt"),
    "change_vs_last": ("token_diet.market_watcher", "change_vs_last"),
    "check_action": ("token_diet.mistake_learner", "check_action"),
    "check_coherence": ("token_diet.claim_check", "check_coherence"),
    "check_critical_facts": ("token_diet.equivalence_gate", "check_critical_facts"),
    "check_fact": ("token_diet.equivalence_gate", "check_fact"),
    "check_plan_coverage": ("token_diet.reasoning_kit", "check_plan_coverage"),
    "check_toolchain": ("token_diet.apk_builder", "check_toolchain"),
    "choose_cognition_strategy": ("token_diet.cognition_arsenal", "choose_cognition_strategy"),
    "choose_language": ("token_diet.context_memory", "choose_language"),
    "claim_check_prompt": ("token_diet.claim_check", "claim_check_prompt"),
    "classify": ("token_diet.rapid_context", "classify"),
    "classify_and_compress": ("token_diet.dynamic_ratio", "classify_and_compress"),
    "classify_turn": ("token_diet.agent_context", "classify_turn"),
    "cleared_marker": ("token_diet.playbooks", "cleared_marker"),
    "click_text": ("token_diet.universal_screen", "click_text"),
    "clone_complete": ("token_diet.progressive_clone", "clone_complete"),
    "clone_skeleton": ("token_diet.progressive_clone", "clone_skeleton"),
    "closest_key": ("token_diet.design_tokens", "closest_key"),
    "code_budget": ("token_diet.polyglot", "code_budget"),
    "code_review_prompt": ("token_diet.code_quality", "code_review_prompt"),
    "coding_actions": ("token_diet.goal_planner", "coding_actions"),
    "cognitive_solve": ("token_diet.cognition_arsenal", "cognitive_solve"),
    "compact_digest": ("token_diet.telegram_market_feed", "compact_digest"),
    "company_keywords": ("token_diet.market_sentiment", "company_keywords"),
    "compare_llm_quality": ("token_diet.smart_multiplier", "compare_llm_quality"),
    "compress_agent_context": ("token_diet.agent_context", "compress_agent_context"),
    "compress_csv": ("token_diet.compression_arsenal", "compress_csv"),
    "compress_history": ("token_diet.session_handoff", "compress_history"),
    "compress_json": ("token_diet.json_compressor", "compress_json"),
    "compress_json_ast": ("token_diet.ast_json_compressor", "compress_json_ast"),
    "compress_json_schema": ("token_diet.compression_arsenal", "compress_json_schema"),
    "compress_ml": ("token_diet.ml_compressor", "compress_ml"),
    "compress_prose_aggressive": ("token_diet.loss_router", "compress_prose_aggressive"),
    "compress_reasoning": ("token_diet.sherlock_reasoner", "compress_reasoning"),
    "compress_retrieved_context": ("token_diet.core", "compress_retrieved_context"),
    "compress_schema": ("token_diet.schema_compressor", "compress_schema"),
    "compress_thought": ("token_diet.reasoning_kit", "compress_thought"),
    "compress_tool_output": ("token_diet.loss_router", "compress_tool_output"),
    "compress_tool_result_json": ("token_diet.json_compressor", "compress_tool_result"),
    "compress_with_routing": ("token_diet.loss_router", "compress_with_routing"),
    "confident_rewrite": ("token_diet.self_belief", "confident_rewrite"),
    "configure_all": ("token_diet.auto_setup", "configure_all"),
    "configure_telegram_mcp": ("token_diet.auto_setup", "configure_telegram_mcp"),
    "correlation_matrix": ("token_diet.risk_metrics", "correlation_matrix"),
    "cosine_similarity": ("token_diet.core", "cosine_similarity"),
    "count_tokens": ("token_diet.core", "count_tokens"),
    "cove_draft_prompt": ("token_diet.reasoning_kit", "cove_draft_prompt"),
    "cove_synthesis_prompt": ("token_diet.reasoning_kit", "cove_synthesis_prompt"),
    "create_android_project": ("token_diet.apk_builder", "create_android_project"),
    "create_app": ("token_diet.server", "create_app"),
    "cron_matches": ("token_diet.workflow_engine", "cron_matches"),
    "crush_json": ("token_diet.headroom", "crush_json"),
    "crush_logs": ("token_diet.headroom", "crush_logs"),
    "crush_markdown": ("token_diet.headroom", "crush_markdown"),
    "date_anchor_block": ("token_diet.date_anchor", "date_anchor_block"),
    "days_until": ("token_diet.date_anchor", "days_until"),
    "decide": ("token_diet.commander", "decide"),
    "decide_action": ("token_diet.rapid_context", "decide_action"),
    "decompose_and_solve": ("token_diet.cognition_arsenal", "decompose_and_solve"),
    "deduplicate_chunks": ("token_diet.core", "deduplicate_chunks"),
    "default_chain_path": ("token_diet.audit_chain", "default_chain_path"),
    "default_registry": ("token_diet.lazy_skills", "default_registry"),
    "demo_goal": ("token_diet.goal_planner", "demo_goal"),
    "describe_findings": ("token_diet.code_quality", "describe_findings"),
    "describe_horizon": ("token_diet.date_anchor", "describe_horizon"),
    "detect_and_report": ("token_diet.auto_setup", "detect_and_report"),
    "detect_breakout": ("token_diet.momentum", "detect_breakout"),
    "detect_code_smells": ("token_diet.code_quality", "detect_code_smells"),
    "detect_content_type": ("token_diet.headroom", "detect_content_type"),
    "detect_language": ("token_diet.polyglot", "detect_language"),
    "detect_overthinking": ("token_diet.efficient_thinking", "detect_overthinking"),
    "detect_patterns": ("token_diet.candlestick_patterns", "detect_patterns"),
    "detect_platform": ("token_diet.universal_screen", "detect_platform"),
    "detect_providers": ("token_diet.provider_registry", "detect_providers"),
    "detect_tickers": ("token_diet.telegram_market_feed", "detect_tickers"),
    "detect_tools": ("token_diet.auto_setup", "detect_tools"),
    "deterministic_judge": ("token_diet.equivalence_gate", "deterministic_judge"),
    "difficulty": ("token_diet.metacognition", "difficulty"),
    "dividend_yield": ("token_diet.moex_feed", "dividend_yield"),
    "docs_bundle": ("token_diet.live_docs", "docs_bundle"),
    "droid_ambiguity": ("token_diet.factory_droid", "ambiguity"),
    "droid_build_knowledge": ("token_diet.factory_droid", "build_repo_knowledge"),
    "droid_classify": ("token_diet.factory_droid", "classify_task"),
    "droid_plan": ("token_diet.factory_droid", "droid_plan"),
    "droid_resolve": ("token_diet.factory_droid", "resolve_ambiguity"),
    "droid_status_block": ("token_diet.factory_droid", "droid_status_block"),
    "dynamic_pipeline": ("token_diet.dynamic_ratio", "dynamic_pipeline"),
    "earned_confidence": ("token_diet.self_belief", "earned_confidence"),
    "ema": ("token_diet.technical_indicators", "ema"),
    "escalate": ("token_diet.reasoning_kit", "escalate"),
    "estimate_complexity": ("token_diet.core", "estimate_complexity"),
    "estimate_design_savings": ("token_diet.design_tokens", "estimate_design_savings"),
    "estimate_docs_savings": ("token_diet.docs_retriever", "estimate_docs_savings"),
    "estimate_effort": ("token_diet.efficient_thinking", "estimate_effort"),
    "estimate_gateway_savings": ("token_diet.open_generative", "estimate_gateway_savings"),
    "estimate_headroom_savings": ("token_diet.headroom", "estimate_headroom_savings"),
    "estimate_keepalive_savings": ("token_diet.cache_keepalive", "estimate_keepalive_savings"),
    "estimate_memory_injection_savings": ("token_diet.claude_mem", "estimate_memory_injection_savings"),
    "estimate_memory_savings": ("token_diet.obsidian_memory", "estimate_memory_savings"),
    "estimate_mixed_savings": ("token_diet.model_router", "estimate_mixed_savings"),
    "estimate_price_range": ("token_diet.market_intelligence", "estimate_price_range"),
    "estimate_schema_savings": ("token_diet.schema_compressor", "estimate_schema_savings"),
    "estimate_scrape_savings": ("token_diet.scrape_graph", "estimate_scrape_savings"),
    "estimate_tabs_savings": ("token_diet.ponytail", "estimate_tabs_savings"),
    "estimate_ui_savings": ("token_diet.ui_context", "estimate_ui_savings"),
    "evaluate_condition": ("token_diet.workflow_engine", "evaluate_condition"),
    "expand": ("token_diet.global_vars", "expand"),
    "expand_layer": ("token_diet.progressive_clone", "expand_layer"),
    "extract_across_chunks": ("token_diet.scrape_graph", "extract_across_chunks"),
    "extract_claims": ("token_diet.reasoning_kit", "extract_claims"),
    "extract_design_tokens": ("token_diet.design_tokens", "extract_design_tokens"),
    "extract_entities": ("token_diet.graph_memory", "extract_entities"),
    "extract_events": ("token_diet.context_memory", "extract_events"),
    "extract_facts": ("token_diet.session_handoff", "extract_facts"),
    "extract_interactive_elements": ("token_diet.ui_context", "extract_interactive_elements"),
    "extract_json_ld": ("token_diet.scrape_graph", "extract_json_ld"),
    "extract_meta_tags": ("token_diet.scrape_graph", "extract_meta_tags"),
    "extract_numbers": ("token_diet.graph_memory", "extract_numbers"),
    "extract_relevant": ("token_diet.webpilot", "extract_relevant"),
    "extract_schema_fields": ("token_diet.scrape_graph", "extract_schema_fields"),
    "extractive_summarize": ("token_diet.map_reduce", "extractive_summarize"),
    "feed_price_event": ("token_diet.market_watcher", "feed_price_event"),
    "feed_to_news_items": ("token_diet.telegram_market_feed", "feed_to_news_items"),
    "fetch_package_docs": ("token_diet.live_docs", "fetch_package_docs"),
    "filter_trading_days": ("token_diet.date_anchor", "filter_trading_days"),
    "find_analogies": ("token_diet.step_back", "find_analogies"),
    "find_android_jar": ("token_diet.apk_builder", "find_android_jar"),
    "find_build_tools": ("token_diet.apk_builder", "find_build_tools"),
    "find_by_text": ("token_diet.scrapling_diet", "find_by_text"),
    "find_hardcoded_verdicts": ("token_diet.claim_check", "find_hardcoded_verdicts"),
    "find_local_telegram_sessions": ("token_diet.auto_setup", "find_local_telegram_sessions"),
    "find_sdk": ("token_diet.apk_builder", "find_sdk"),
    "find_sdkmanager": ("token_diet.apk_builder", "find_sdkmanager"),
    "fingerprint": ("token_diet.cache_breakpoints", "fingerprint"),
    "firm_up": ("token_diet.self_belief", "firm_up"),
    "flag_uncertainty": ("token_diet.metacognition", "flag_uncertainty"),
    "flush_cache": ("token_diet.live_docs", "flush_cache"),
    "format_date_iso": ("token_diet.date_anchor", "format_date_iso"),
    "format_date_ru": ("token_diet.date_anchor", "format_date_ru"),
    "format_date_short": ("token_diet.date_anchor", "format_date_short"),
    "format_for_model": ("token_diet.intelligence_chain", "format_for_model"),
    "from_fresh_news": ("token_diet.market_sentiment", "from_fresh_news"),
    "from_pulse": ("token_diet.market_sentiment", "from_pulse"),
    "full_date_context": ("token_diet.date_anchor", "full_date_context"),
    "full_plan": ("token_diet.commander", "full_plan"),
    "full_status": ("token_diet.status", "full_status"),
    "fuzzy_fingerprint": ("token_diet.tool_output_pruner", "fuzzy_fingerprint"),
    "gather_sentiment_texts": ("token_diet.market_sentiment", "gather_sentiment_texts"),
    "generate_shell_config": ("token_diet.auto_setup", "generate_shell_config"),
    "generate_signal": ("token_diet.market_intelligence", "generate_signal"),
    "geopolitics": ("token_diet.geopolitics", "geo_verdict"),
    "geopolitics_block": ("token_diet.geopolitics", "market_context_block"),
    "get_live_docs": ("token_diet.live_docs", "get_live_docs"),
    "get_post_comments": ("token_diet.pulse_reader", "get_post_comments"),
    "get_telegram_mcp_env": ("token_diet.auto_setup", "get_telegram_mcp_env"),
    "get_ticker_posts": ("token_diet.pulse_reader", "get_ticker_posts"),
    "get_token": ("token_diet.tinkoff_invest", "get_token"),
    "get_user_posts": ("token_diet.pulse_reader", "get_user_posts"),
    "get_var": ("token_diet.global_vars", "get_var"),
    "guarded_records": ("token_diet.core", "guarded_records"),
    "guarded_tool_schemas": ("token_diet.tool_schema_compressor", "guarded_tool_schemas"),
    "hash_text": ("token_diet.cache_breakpoints", "hash_text"),
    "headroom_compress": ("token_diet.headroom", "headroom_compress"),
    "headroom_retrieve": ("token_diet.headroom", "headroom_retrieve"),
    "historical_var": ("token_diet.risk_metrics", "historical_var"),
    "history": ("token_diet.pnl_journal", "history"),
    "history_budget": ("token_diet.playbooks", "history_budget"),
    "html_to_text": ("token_diet.clean_scraper", "html_to_text"),
    "hybrid_search": ("token_diet.hybrid_search", "hybrid_search"),
    "init_rules": ("token_diet.market_watcher", "init_rules"),
    "inject_date_anchor": ("token_diet.date_anchor", "inject_date_anchor"),
    "inject_methodology": ("token_diet.intelligence_chain", "inject_methodology"),
    "inspect_apk": ("token_diet.apk_builder", "inspect_apk"),
    "install_instructions": ("token_diet.apk_builder", "install_instructions"),
    "install_telegram_mcp": ("token_diet.auto_setup", "install_telegram_mcp"),
    "interval_strategy": ("token_diet.trading_robot", "interval_strategy"),
    "is_bot_like_ua": ("token_diet.ui_context", "is_bot_like_ua"),
    "is_coherent": ("token_diet.strix_stealth", "is_coherent"),
    "is_market_open": ("token_diet.market_watcher", "is_market_open"),
    "is_private_ip": ("token_diet.workflow_engine", "is_private_ip"),
    "is_trading_day": ("token_diet.market_watcher", "is_trading_day"),
    "is_weekend": ("token_diet.date_anchor", "is_weekend"),
    "journal_block": ("token_diet.pnl_journal", "journal_block"),
    "latest_patterns": ("token_diet.candlestick_patterns", "latest_patterns"),
    "ld_flatten": ("token_diet.scrape_graph", "ld_flatten"),
    "learn_from": ("token_diet.mistake_learner", "learn_from"),
    "leverage_analysis": ("token_diet.portfolio_commander", "leverage_analysis"),
    "link_local_telegram_session": ("token_diet.auto_setup", "link_local_telegram_session"),
    "lint_feedback_prompt": ("token_diet.code_quality", "lint_feedback_prompt"),
    "lint_iterate": ("token_diet.code_quality", "lint_iterate"),
    "live_scan": ("token_diet.live_scan", "scan_market"),
    "live_scan_cli": ("token_diet.live_scan", "run_scan"),
    "ltm_decompose_prompt": ("token_diet.reasoning_kit", "ltm_decompose_prompt"),
    "ltm_solve_prompt": ("token_diet.reasoning_kit", "ltm_solve_prompt"),
    "ma_cross": ("token_diet.trading_robot", "ma_cross"),
    "make_document_toc": ("token_diet.compression_arsenal", "make_document_toc"),
    "map_reduce": ("token_diet.map_reduce", "map_reduce"),
    "map_to_tailwind": ("token_diet.design_tokens", "map_to_tailwind"),
    "mark_static": ("token_diet.cache_master", "mark_static"),
    "market_classify": ("token_diet.market_search", "classify"),
    "market_info": ("token_diet.market_search", "market_info"),
    "market_open_now": ("token_diet.trading_robot", "market_open_now"),
    "max_drawdown": ("token_diet.risk_metrics", "max_drawdown"),
    "mean_ci": ("token_diet.equivalence_gate", "mean_ci"),
    "metacognition_prompt": ("token_diet.metacognition", "metacognition_prompt"),
    "mfi": ("token_diet.technical_indicators", "mfi"),
    "minimize_system_prompt": ("token_diet.context_engineering", "minimize_system_prompt"),
    "model_analyst": ("token_diet.model_army", "ask_analyst"),
    "model_army_verdict": ("token_diet.model_army", "army_verdict"),
    "model_ask": ("token_diet.model_army", "ask"),
    "model_brain": ("token_diet.model_army", "ask_brain"),
    "model_fast": ("token_diet.model_army", "ask_fast"),
    "model_gemini": ("token_diet.model_army", "ask_gemini"),
    "model_generator": ("token_diet.model_army", "ask_generator"),
    "model_omni": ("token_diet.model_army", "ask_omni"),
    "momentum_lean": ("token_diet.momentum", "momentum_lean"),
    "monitor_loop": ("token_diet.market_guard", "monitor_loop"),
    "multi_agent_debate": ("token_diet.cognition_arsenal", "multi_agent_debate"),
    "n_trading_days_ahead": ("token_diet.date_anchor", "n_trading_days_ahead"),
    "network_capture": ("token_diet.scrapling_diet", "network_capture"),
    "never_translate": ("token_diet.context_memory", "never_translate"),
    "news_block": ("token_diet.market_guard", "news_block"),
    "news_sweep": ("token_diet.market_guard", "news_sweep"),
    "next_dividends": ("token_diet.moex_feed", "next_dividends"),
    "next_trading_day": ("token_diet.date_anchor", "next_trading_day"),
    "normalize_payload": ("token_diet.open_generative", "normalize_payload"),
    "normalize_question": ("token_diet.question_normalizer", "normalize_question"),
    "now": ("token_diet.date_anchor", "now"),
    "obv": ("token_diet.technical_indicators", "obv"),
    "obv_trend": ("token_diet.technical_indicators", "obv_trend"),
    "optimize_system_prompt": ("token_diet.context_engineering", "optimize_system_prompt"),
    "optimize_thinking": ("token_diet.efficient_thinking", "optimize_thinking"),
    "pack_records": ("token_diet.core", "pack_records"),
    "parse_date": ("token_diet.investment_analyzer", "parse_date"),
    "parse_ddl": ("token_diet.schema_compressor", "parse_ddl"),
    "parse_duration_secs": ("token_diet.workflow_engine", "parse_duration_secs"),
    "parse_message": ("token_diet.telegram_market_feed", "parse_message"),
    "parse_post": ("token_diet.pulse_reader", "parse_post"),
    "parse_workflow": ("token_diet.workflow_engine", "parse_workflow"),
    "patterns_block": ("token_diet.candlestick_patterns", "patterns_block"),
    "payload_key": ("token_diet.open_generative", "payload_key"),
    "percentile_corridor": ("token_diet.trading_robot", "percentile_corridor"),
    "persist": ("token_diet.self_belief", "persist"),
    "plan_and_solve_prompt": ("token_diet.reasoning_kit", "plan_and_solve_prompt"),
    "plan_cache": ("token_diet.cache_master", "plan_cache"),
    "plan_position": ("token_diet.portfolio_commander", "plan_position"),
    "plan_steps": ("token_diet.reasoning_kit", "plan_steps"),
    "position_plan": ("token_diet.trading_robot", "position_plan"),
    "position_size": ("token_diet.risk_metrics", "position_size"),
    "prepare_request": ("token_diet.core", "prepare_request"),
    "prior_confidence": ("token_diet.metacognition", "prior_confidence"),
    "project_fields": ("token_diet.core", "project_fields"),
    "protect_code": ("token_diet.polyglot", "protect_code"),
    "providers_ask_all": ("token_diet.provider_registry", "ask_all"),
    "providers_ask_any": ("token_diet.provider_registry", "ask_any"),
    "prune_and_compress": ("token_diet.tool_output_pruner", "prune_and_compress"),
    "prune_history": ("token_diet.playbooks", "prune_history"),
    "prune_tool_outputs": ("token_diet.tool_output_pruner", "prune_tool_outputs"),
    "pulse_comment": ("token_diet.pulse_writer", "comment"),
    "pulse_cookies_from_file": ("token_diet.pulse_writer", "load_cookies_from_file"),
    "pulse_cookies_from_firefox": ("token_diet.pulse_writer", "load_cookies_from_firefox"),
    "pulse_digest": ("token_diet.pulse_reader", "digest"),
    "pulse_like": ("token_diet.pulse_writer", "like_post"),
    "pulse_post": ("token_diet.pulse_writer", "post_text"),
    "pulse_sentiment": ("token_diet.pulse_reader", "pulse_sentiment"),
    "pulse_validate_text": ("token_diet.pulse_writer", "validate_text"),
    "quality_report": ("token_diet.code_quality", "quality_report"),
    "quick_action": ("token_diet.rapid_context", "quick_action"),
    "rank": ("token_diet.hybrid_search", "rank"),
    "rate_of_change": ("token_diet.momentum", "rate_of_change"),
    "read_page": ("token_diet.webpilot", "read_page"),
    "record": ("token_diet.pnl_journal", "record"),
    "reduce_output": ("token_diet.loss_router", "reduce_output"),
    "register_telegram_mcp": ("token_diet.auto_setup", "register_telegram_mcp"),
    "relocate": ("token_diet.cache_master", "relocate"),
    "remember": ("token_diet.intelligence_chain", "remember"),
    "render": ("token_diet.progressive_clone", "render"),
    "render_accessibility_tree": ("token_diet.ui_context", "render_accessibility_tree"),
    "render_compressed_context": ("token_diet.agent_context", "render_compressed_context"),
    "render_handoff": ("token_diet.session_handoff", "render_handoff"),
    "render_pruned": ("token_diet.tool_output_pruner", "render_pruned"),
    "render_schema": ("token_diet.schema_compressor", "render_schema"),
    "render_status": ("token_diet.status", "render_status"),
    "render_ui_context": ("token_diet.ui_context", "render_ui_context"),
    "reorder_prompt": ("token_diet.context_engineering", "reorder_prompt"),
    "report_text": ("token_diet.system_turbo", "report_text"),
    "rerank_chunks": ("token_diet.bm25_reranker", "rerank_chunks"),
    "rerank_library": ("token_diet.bm25_reranker", "rerank_library"),
    "resolve_figi": ("token_diet.tinkoff_invest", "resolve_figi"),
    "resolve_template": ("token_diet.workflow_engine", "resolve_template"),
    "result_hash": ("token_diet.tool_output_pruner", "result_hash"),
    "retention_prompt": ("token_diet.reasoning_kit", "retention_prompt"),
    "returns_of": ("token_diet.risk_metrics", "returns_of"),
    "review_code": ("token_diet.code_quality", "review_code"),
    "rewrite_surrender": ("token_diet.self_belief", "rewrite_surrender"),
    "risk_block": ("token_diet.risk_metrics", "risk_block"),
    "risk_report": ("token_diet.risk_metrics", "risk_report"),
    "rotate_profiles": ("token_diet.strix_stealth", "rotate_profiles"),
    "route_and_estimate": ("token_diet.model_router", "route_and_estimate"),
    "route_query": ("token_diet.model_router", "route_query"),
    "run_on_tinkoff": ("token_diet.trading_robot", "run_on_tinkoff"),
    "run_strategies": ("token_diet.trading_robot", "run_strategies"),
    "save_token": ("token_diet.tinkoff_invest", "save_token"),
    "savings_report": ("token_diet.progressive_clone", "savings_report"),
    "schema_to_prompt_block": ("token_diet.schema_compressor", "schema_to_prompt_block"),
    "score_prompt_sections": ("token_diet.neural_scorer", "score_prompt_sections"),
    "score_sentiment": ("token_diet.market_intelligence", "score_sentiment"),
    "scrape_and_save": ("token_diet.clean_scraper", "scrape_and_save"),
    "scrape_cli": ("token_diet.scrapling_diet", "scrape_cli"),
    "scrape_url": ("token_diet.clean_scraper", "scrape_url"),
    "screenshot": ("token_diet.universal_screen", "screenshot"),
    "search_keywords": ("token_diet.pulse_reader", "search_keywords"),
    "search_vault": ("token_diet.hybrid_search", "search_vault"),
    "see_and_click": ("token_diet.universal_screen", "see_and_click"),
    "self_critique": ("token_diet.metacognition", "self_critique"),
    "serve_main": ("token_diet.server", "main"),
    "set_var": ("token_diet.global_vars", "set_var"),
    "sharpe_ratio": ("token_diet.risk_metrics", "sharpe_ratio"),
    "sherlock_system_prompt": ("token_diet.sherlock_reasoner", "sherlock_system_prompt"),
    "single_bar_patterns": ("token_diet.candlestick_patterns", "single_bar_patterns"),
    "sma": ("token_diet.technical_indicators", "sma"),
    "smart_prompt": ("token_diet.intelligence_chain", "smart_prompt"),
    "snapshot": ("token_diet.pnl_journal", "snapshot"),
    "snapshot_block": ("token_diet.market_guard", "snapshot_block"),
    "sortino_ratio": ("token_diet.risk_metrics", "sortino_ratio"),
    "split_into_chunks": ("token_diet.map_reduce", "split_into_chunks"),
    "stealth_fingerprint": ("token_diet.ui_context", "stealth_fingerprint"),
    "step_back_prompt": ("token_diet.step_back", "step_back_prompt"),
    "step_back_question": ("token_diet.step_back", "step_back_question"),
    "stochastic": ("token_diet.technical_indicators", "stochastic"),
    "stop_loss_level": ("token_diet.trading_robot", "stop_loss_level"),
    "stress_block": ("token_diet.market_guard", "stress_block"),
    "stress_test": ("token_diet.market_guard", "stress_test"),
    "strip_apology": ("token_diet.self_belief", "strip_apology"),
    "strip_fluff": ("token_diet.decisive_agent", "strip_fluff"),
    "strip_noise": ("token_diet.neural_scorer", "strip_noise"),
    "structpack_roundtrip_safe": ("token_diet.core", "structpack_roundtrip_safe"),
    "supervised_agent_loop": ("token_diet.agent_supervisor", "supervised_agent_loop"),
    "sweet_report": ("token_diet.sweet_spot", "report"),
    "sweet_scan": ("token_diet.sweet_spot", "scan"),
    "system_prompt_for": ("token_diet.polyglot", "system_prompt_for"),
    "tailwind_class_for": ("token_diet.design_tokens", "tailwind_class_for"),
    "tdd_flow": ("token_diet.code_quality", "tdd_flow"),
    "technical_snapshot": ("token_diet.technical_indicators", "technical_snapshot"),
    "telegram_load_token": ("token_diet.telegram_commander", "load_token"),
    "telegram_mcp_installed": ("token_diet.auto_setup", "telegram_mcp_installed"),
    "telegram_run": ("token_diet.telegram_commander", "run"),
    "telegram_send_message": ("token_diet.telegram_commander", "send_message"),
    "tg_intel": ("token_diet.tg_intel", "tg_intel"),
    "tg_merge_and_rank": ("token_diet.tg_intel", "merge_and_rank"),
    "tg_scout": ("token_diet.tg_scout", "scout"),
    "tg_scout_block": ("token_diet.tg_scout", "scout_block"),
    "three_bar_patterns": ("token_diet.candlestick_patterns", "three_bar_patterns"),
    "tinkoff_status": ("token_diet.tinkoff_invest", "status"),
    "to_tron": ("token_diet.tron_format", "to_tron"),
    "to_tron_schemas": ("token_diet.tron_format", "to_tron_schemas"),
    "today": ("token_diet.date_anchor", "today"),
    "top_by_yield": ("token_diet.moex_feed", "top_by_yield"),
    "top_memory_processes": ("token_diet.system_turbo", "top_memory_processes"),
    "trade_commission": ("token_diet.autopilot", "commission_cost"),
    "trade_plan": ("token_diet.risk_metrics", "trade_plan"),
    "trading_days_between": ("token_diet.date_anchor", "trading_days_between"),
    "trading_days_until": ("token_diet.date_anchor", "trading_days_until"),
    "trailing_stop": ("token_diet.risk_metrics", "trailing_stop"),
    "translation_safe": ("token_diet.context_memory", "translation_safe"),
    "tree_of_thoughts": ("token_diet.cognition_arsenal", "tree_of_thoughts"),
    "tron_roundtrip_safe": ("token_diet.tron_format", "tron_roundtrip_safe"),
    "tron_savings": ("token_diet.tron_format", "savings"),
    "truncate_tool_result": ("token_diet.agent_supervisor", "truncate_tool_result"),
    "turbo": ("token_diet.system_turbo", "turbo"),
    "two_bar_patterns": ("token_diet.candlestick_patterns", "two_bar_patterns"),
    "unpack_records": ("token_diet.core", "unpack_records"),
    "verify_claim": ("token_diet.claim_check", "verify_claim"),
    "verify_claims": ("token_diet.reasoning_kit", "verify_claims"),
    "verify_command": ("token_diet.intelligence_chain", "verify_command"),
    "volume_profile": ("token_diet.trading_robot", "volume_profile"),
    "watch": ("token_diet.market_watcher", "watch"),
    "web_extract_links": ("token_diet.web_agent", "extract_links"),
    "web_search": ("token_diet.webpilot", "search"),
    "web_visit": ("token_diet.web_agent", "visit"),
    "web_visit_and_save": ("token_diet.web_agent", "visit_and_save"),
    "weekday_ru": ("token_diet.date_anchor", "weekday_ru"),
    "williams_r": ("token_diet.technical_indicators", "williams_r"),
    "write_shell_config": ("token_diet.auto_setup", "write_shell_config"),
}

import importlib
import typing as _typing

_LAZY_IMPORTS.update({
    "Anomaly": ("token_diet.spend_forecast", "Anomaly"),
    "Holding": ("token_diet.rebalance_advisor", "Holding"),
    "RebalancePlan": ("token_diet.rebalance_advisor", "RebalancePlan"),
    "SpendForecast": ("token_diet.spend_forecast", "SpendForecast"),
    "TradeAdvice": ("token_diet.rebalance_advisor", "TradeAdvice"),
    "UsageDay": ("token_diet.spend_forecast", "UsageDay"),
    "budget_runway": ("token_diet.spend_forecast", "budget_runway"),
    "drift_report": ("token_diet.rebalance_advisor", "drift_report"),
    "forecast_from_pairs": ("token_diet.spend_forecast", "forecast_from_pairs"),
    "forecast_spend": ("token_diet.spend_forecast", "forecast_spend"),
    "rebalance_plan": ("token_diet.rebalance_advisor", "rebalance_plan"),
})


def __getattr__(name: str) -> _typing.Any:
    if name in _LAZY_IMPORTS:
        mod_name, attr = _LAZY_IMPORTS[name]
        mod = importlib.import_module(mod_name)
        val = getattr(mod, attr)
        globals()[name] = val
        return val
    # submodule fallback: e.g. token_diet.core
    try:
        mod = importlib.import_module(f"token_diet.{name}")
        globals()[name] = mod
        return mod
    except ImportError:
        pass
    raise AttributeError(f"module 'token_diet' has no attribute {name!r}")

def __dir__() -> list[str]:
    return sorted(list(__all__) + list(_LAZY_IMPORTS.keys()))

